spring:
  application:
    name: baseball-api
management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      jmx:
        domain: 'io.retro.baseball-api.metrics'
io:
  retro:
    baseball:
      datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: changeme
        username: changeme
        password: changeme
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          poolName: Hikari
          auto-commit: false
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
            autoReconnect: false